services:
  aviswitch:
    image: ghcr.io/aiqinxuancai/aviswitch:latest
    container_name: aviswitch
    restart: unless-stopped
    ports:
      - "7085:7085"
    volumes:
      - ./config.toml:/app/config.toml:ro
    environment:
      - AVISWITCH_CONFIG=/app/config.toml
